### ISSUE TITLE
add ci cd workflow

### ISSUE THREAD

**Issue by ananyag309** [Vishwajith-Shettigar/NextGen#112]
"Add a CI/CD workflow `.yml` file to automate build, test, and deployment processes on every push or pull request to the `main` branch. This ensures code quality and streamlines the deployment pipeline."

**Comment by codewithaaryaman707** [comment]
i want to work on it

**Comment by Saumy1905** [comment]
Hi @ananyag309 @Vishwajith-Shettigar, I've submitted a PR (#112) that resolves this issue. Please take a look and let me know if any changes are required.

Could you also please add the **relevant labels** to this PR so it's marked correctly?

Thank you!
