### ISSUE TITLE
[Feature request] : Implement Icebreaker Prompts for Smoother Interactions

### ISSUE THREAD

**Issue by sanchitc05** [Vishwajith-Shettigar/NextGen#141]
**Description:**

To enhance the user experience and facilitate more natural interactions, we propose adding a feature that provides icebreaker prompts or questions. These prompts will be displayed to users when they initiate a new conversation, especially when interacting with someone for the first time. 

**Proposed Implementation:**

1. **Prompt Library:**
   * Create a database of carefully curated icebreaker prompts, categorized by various interests or situations.
   * Consider prompts like "What's the most interesting thing you've learned recently?" or "If you could have any superpower, what would it be and why?"
2. **Prompt Delivery:**
   * When a user starts a new chat, the app can randomly select a relevant prompt from the library and display it subtly within the chat interface.
   * The prompt can be optional and can be disabled by the user if they prefer to start the conversation without a prompt.
3. **User-Generated Prompts:**
   * Allow users to submit their own icebreaker prompts, which can be reviewed and added to the library after moderation. 

**Benefits:**
* **Reduced Awkwardness:** Prompts can help break the ice and encourage more natural conversations.
* **Enhanced User Experience:** A smoother and more engaging user experience can lead to increased user satisfaction and retention.
* **Community Building:** Shared prompts can foster a sense of community and shared experiences.

**Potential Challenges:**
* **Prompt Quality:** Ensuring the quality and relevance of prompts may require careful curation and moderation.
* **User Preference:** Some users may prefer to start conversations without prompts.

By implementing this feature, we can significantly improve the quality of interactions on the platform and make it easier for users to connect with each other.

**Please let me know if you have any questions or would like to discuss this further.**

**Comment by Saumy1905** [comment]
I would like to work on this issue . Can you assign it to me?
