### ISSUE TITLE
[Feature] Change default marker to default image avatar.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [Vishwajith-Shettigar/NextGen#36]
In our map when we show nearby users, we shows images only if image URL is not null, otherwise we show default red marker. Instead of showing red marker, show default image avatar. 

**Additional Context.**
NearByFragment.kt
person_24.xml(for default avatar)

**Comment by Varsha567** [comment]
I would like to work on this issue as I have experience working with Android Studio. Could you please assign this issue to me?

**Comment by TaniyaRajesh** [comment]
Hey, I would like to work on this issue #36

**Comment by Gopal0Gupta** [comment]
@Vishwajith-Shettigar please assign me this issue under hacktoberfest & gssoc-ext.
