### ISSUE TITLE
[Enhancement] Remove all unused imports from files.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [Vishwajith-Shettigar/NextGen#41]
Remove all unused imports from all files.

**Comment by LegendCK** [comment]
Hey , @Vishwajith-Shettigar  can you assign this to me under Gssoc-ext

**Comment by Amit-4186** [comment]
Hey, @Vishwajith-Shettigar can you please assign this issue to me for gssoc-ext

**Comment by Vishwajith-Shettigar** [comment]
@Amit-4186 this issue already assigned, you can work on  #44 .
