### ISSUE TITLE
[Bug] app crash when location is granted

### ISSUE THREAD

**Issue by utkarsh006** [Vishwajith-Shettigar/NextGen#43]
- app is crashing when user launches it for the first time.

**Comment by Vishwajith-Shettigar** [comment]
Can you please add stack trace of error you encountered ?

**Comment by utkarsh006** [comment]
@Vishwajith-Shettigar here's the [stacktrace](https://stackoverflow.com/questions/77241123/starting-tgs-with-type-location-targetsdk-34-android-14-crash-on-startup)
