### ISSUE TITLE
[Enhancement] Change layout of Privacy Screen.

### ISSUE THREAD

**Issue by utkarsh006** [Vishwajith-Shettigar/NextGen#45]
- Refactor the layouts of Privacy Screen to constraint layout.
- Why prefer Constraint layouts? [Article](https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html)

**Comment by utkarsh006** [comment]
@Vishwajith-Shettigar please assign me this issue under hacktoberfest.

**Comment by AdarshThakare** [comment]
@Vishwajith-Shettigar I would love to work on this issue. Please assign me this issue.

**Comment by AdarshThakare** [comment]
@utkarsh006 are u working on this?

**Comment by Vishwajith-Shettigar** [comment]
@AdarshThakare have a look at #81. Im closing this since it is duplicate, I'll review your PR no worries.
