### ISSUE TITLE
Add App Logo

### ISSUE THREAD

**Issue by amitthecoder** [Vishwajith-Shettigar/NextGen#48]
![WhatsApp Image 2024-10-04 at 18 59 17_47ac14d2](https://github.com/user-attachments/assets/5652acfb-2836-4c6e-b54b-cfd7a9388a47)

**Comment by indra057** [comment]
can i work on this issue and please tell me or describe me what the logo should be or u can give me the image

**Comment by Amit-4186** [comment]
Also If possible can you please add hacktoberfest tag to the repo. It would really be helpful.
