### ISSUE TITLE
Proposal for Updating README File

### ISSUE THREAD

**Issue by Ankesh-erek** [Vishwajith-Shettigar/NextGen#62]
This proposal aims to update the current README file for the NextGen GitHub repository to provide clear instructions on how to set up, contribute, and follow contribution guidelines. This will make the project more accessible to new contributors and foster a welcoming environment for open-source collaboration.

Key Additions:
-----------------
**Setup Guide**
o  Detailed steps for forking and cloning the repository.
o  Instructions for building and running the project in Android Studio.
**Contribution Guidelines**
o  Clear rules and expectations for contributions.
o  How to submit pull requests (PRs).
o  Information about issue tracking and assigned tasks.
* Could I please be assigned to this issue? Also, could you kindly add the @GSSOC tag and the appropriate level tag? Thank you!

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
and also add gssoc-ext label
