### ISSUE TITLE
Add Eye Icon to Password Field for Visibility Toggle

### ISSUE THREAD

**Issue by akmaurya7** [Vishwajith-Shettigar/NextGen#77]
Currently, the password field in the sign-up/sign-in form does not have an eye icon to toggle the visibility of the entered password. Adding a password visibility toggle icon will enhance the user experience by allowing users to see the password they enter.

**Comment by akmaurya7** [comment]
i would like to work on this functionality.

**Comment by MonuGit9** [comment]
Assign me
