### ISSUE TITLE
[Enhancement] Migrating layouts to constraint layout

### ISSUE THREAD

**Issue by utkarsh006** [Vishwajith-Shettigar/NextGen#81]
- Need to migrate maximum layouts to constraint layouts.
- [Why to migrate to constraint layouts?](https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html)
- Please assign me this issue under hacktoberfest.

- [x] HomeFragment
- [ ] ProfileFragment
- [x] NearByFragment
- [x] SignupFragment
- [ ] SignInFragment
- [ ] MessageFragment
- [ ] EditProfileFragment
- [x] PrivacyFragment 
- [ ] ViewProfileFragment
- [ ] VideoCallFragment
- [x] NotificationFragment

**Comment by Vishwajith-Shettigar** [comment]
This could be done one by one ( screen )

**Comment by Vishwajith-Shettigar** [comment]
Anyone can work on the screens mentioned above one by one. Please mention screen you are working with to avoid conflicts.

**Comment by Vishwajith-Shettigar** [comment]
No need to ask for assignments.

**Comment by Vishwajith-Shettigar** [comment]
@utkarsh006 please feel free to work on any screen. One PR per screen to avoid lot of changes in single PR.

**Comment by akmaurya7** [comment]
Ok sir. So, i am working on notification fragment now.

**Comment by utkarsh006** [comment]
@Vishwajith-Shettigar sure will continue in this way.

**Comment by utkarsh006** [comment]
@Vishwajith-Shettigar can we make sure that one contributor must open one pr at a single time?

**Comment by akmaurya7** [comment]
Got it

**Comment by akmaurya7** [comment]
i will work on nearby_fragment.

**Comment by AdarshThakare** [comment]
i will work on privacy fragment

**Comment by Vishwajith-Shettigar** [comment]
Hi all, you can take other screen after opening PR for previous screen, don't wait for my review. Don't forget to attach screenshot of UI after changes, in PR.

**Comment by akmaurya7** [comment]
Now , i will work on signup fragment

**Comment by AdarshThakare** [comment]
Now , I will work on profile fragment

**Comment by utkarsh006** [comment]
@Vishwajith-Shettigar Request for contributors. Whatever layout you guys are working on, tick the checkbox in the above readme.

**Comment by akmaurya7** [comment]
Now , i will work on the signin fragment

**Comment by AdarshThakare** [comment]
Now I will work on edit Profile fragment

**Comment by AdarshThakare** [comment]
> * Need to migrate maximum layouts to constraint layouts.
> * [Why to migrate to constraint layouts?](https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html)
> * Please assign me this issue under hacktoberfest.
> * [x]  HomeFragment
> * [x]  ProfileFragment
> * [x]  NearByFragment
> * [x]  SignupFragment
> * [x]  SignInFragment
> * [x]  MessageFragment
> * [x]  EditProfileFragment
> * [x]  PrivacyFragment
> * [x]  ViewProfileFragment
> * [x]  VideoCallFragment
> * [x]  NotificationFragment

**Comment by Uditya-Raj** [comment]
Now I will work on ViewProfile Fragment

**Comment by Uditya-Raj** [comment]
Now I will be working on Message Fragment

**Comment by AdarshThakare** [comment]
I will now work on video call fragment

**Comment by akmaurya7** [comment]
Can I work on profile and edit profile fragment which is not migrated yet in the updated project.

**Comment by Darkeye14** [comment]
I have worked on the edit-profile layout and converted it to the constraint Layout! Please do remove it from the List of tasks.
Thank You!

**Comment by akmaurya7** [comment]
@Vishwajith-Shettigar  It will take time for me to work on the above mentioned fragmenr because of semester exam , so you can go with @Darkeye14

**Comment by Darkeye14** [comment]
Thank You!! @akmaurya7
